version: "3.3"
services:
  homepage:
    build: .
    container_name: homepage
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
